"""Initial schema

Revision ID: 1af2e738728e
Revises: 
Create Date: 2026-02-15 21:03:06.948261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af2e738728e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create all tables WITHOUT foreign key constraints first
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Organization name'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL-friendly identifier'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='Organization owner user ID'),
    sa.Column('sso_provider', sa.String(length=50), nullable=True, comment='SSO provider: azure_ad, okta, saml'),
    sa.Column('sso_tenant_id', sa.String(length=255), nullable=True, comment='SSO tenant/realm ID'),
    sa.Column('sso_metadata', sa.JSON(), nullable=False, comment='SSO provider configuration metadata'),
    sa.Column('azure_tenant_id', sa.String(length=255), nullable=True, comment='Azure AD tenant ID for this org'),
    sa.Column('azure_subscription_id', sa.String(length=255), nullable=True, comment='Azure subscription ID'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='Maximum users allowed'),
    sa.Column('max_agents', sa.Integer(), nullable=False, comment='Maximum agents allowed'),
    sa.Column('features_enabled', sa.JSON(), nullable=False, comment='Enabled feature flags'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether organization is active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='Null for SSO-only users'),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Authentication provider'),
    sa.Column('provider_id', sa.String(length=255), nullable=True, comment='Unique ID from SSO provider'),
    sa.Column('sso_subject_id', sa.String(length=255), nullable=True, comment='SSO subject identifier'),
    sa.Column('department', sa.String(length=255), nullable=True, comment="User's department (informational)"),
    sa.Column('job_title', sa.String(length=255), nullable=True, comment="User's job title"),
    sa.Column('organization_id', sa.Uuid(), nullable=True, comment="User's organization (null for super admin)"),
    sa.Column('role', sa.String(length=50), nullable=False, comment='System-level role'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Whether email is verified'),
    sa.Column('email_verification_token', sa.String(length=64), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_secret', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_otp_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=True)
    op.create_index(op.f('ix_users_sso_subject_id'), 'users', ['sso_subject_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment='Agent modality type'),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('provider_config', sa.JSON(), nullable=False),
    sa.Column('type_config', sa.JSON(), nullable=False, comment='Type-specific configuration (voice, chat, email, workflow)'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enabled_tools', sa.JSON(), nullable=False),
    sa.Column('enabled_tool_ids', sa.JSON(), nullable=False),
    sa.Column('tool_configs', sa.JSON(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('embed_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_domains', sa.JSON(), nullable=False),
    sa.Column('embed_settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_type'), 'agents', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agents_public_id'), 'agents', ['public_id'], unique=True)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Provider: azure_foundry, aws_bedrock, google_vertex'),
    sa.Column('azure_endpoint', sa.String(length=500), nullable=True),
    sa.Column('azure_resource_group', sa.String(length=200), nullable=True),
    sa.Column('azure_project_name', sa.String(length=200), nullable=True),
    sa.Column('azure_api_key_encrypted', sa.String(length=500), nullable=True),
    sa.Column('provider_config', sa.JSON(), nullable=False, comment='Additional provider configuration'),
    sa.Column('resource_quotas', sa.JSON(), nullable=False, comment='Resource quotas for this environment'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False, comment='Lock to prevent modifications (e.g., production freeze)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_organization_id'), 'environments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_environments_slug'), 'environments', ['slug'], unique=False)
    op.create_table('privacy_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_collection_consent', sa.Boolean(), nullable=False),
    sa.Column('analytics_consent', sa.Boolean(), nullable=False),
    sa.Column('recording_consent', sa.Boolean(), nullable=False),
    sa.Column('data_retention_days', sa.Integer(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_settings_user_id'), 'privacy_settings', ['user_id'], unique=True)
    op.create_table('units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_unit_org_slug')
    )
    op.create_index(op.f('ix_units_organization_id'), 'units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_units_slug'), 'units', ['slug'], unique=False)
    op.create_table('user_integrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True, comment='Org-level integrations shared across users'),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False, comment='Encrypted integration credentials'),
    sa.Column('settings', sa.JSON(), nullable=False, comment='Integration-specific settings'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_integrations_integration_type'), 'user_integrations', ['integration_type'], unique=False)
    op.create_index(op.f('ix_user_integrations_organization_id'), 'user_integrations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_quotas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False, comment='e.g., voice_minutes, chat_messages, tokens'),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('used_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quotas_user_id'), 'user_quotas', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('agent_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('azure_deployment_id', sa.String(length=255), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False, comment='Frozen config at deployment time'),
    sa.Column('promoted_from_environment_id', sa.Uuid(), nullable=True, comment='Source environment if promoted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_deployments_agent_id'), 'agent_deployments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_deployments_environment_id'), 'agent_deployments', ['environment_id'], unique=False)
    op.create_table('agent_quotas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('used_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_quotas_agent_id'), 'agent_quotas', ['agent_id'], unique=True)
    op.create_table('agent_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False, comment='Full agent configuration at this version'),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False, comment='Denormalized for fast queries'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'slug', name='uq_dept_unit_slug')
    )
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_departments_slug'), 'departments', ['slug'], unique=False)
    op.create_index(op.f('ix_departments_unit_id'), 'departments', ['unit_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Processing status: pending, processing, completed, failed'),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_agent_id'), 'documents', ['agent_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False, comment='Denormalized for fast queries'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'slug', name='uq_project_dept_slug')
    )
    op.create_index(op.f('ix_projects_department_id'), 'projects', ['department_id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_table('hierarchy_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False, comment='Which hierarchy level this membership is for'),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'level', 'organization_id', 'unit_id', 'department_id', 'project_id', name='uq_hierarchy_membership')
    )
    op.create_index(op.f('ix_hierarchy_memberships_department_id'), 'hierarchy_memberships', ['department_id'], unique=False)
    op.create_index(op.f('ix_hierarchy_memberships_organization_id'), 'hierarchy_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hierarchy_memberships_project_id'), 'hierarchy_memberships', ['project_id'], unique=False)
    op.create_index(op.f('ix_hierarchy_memberships_unit_id'), 'hierarchy_memberships', ['unit_id'], unique=False)
    op.create_index(op.f('ix_hierarchy_memberships_user_id'), 'hierarchy_memberships', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False, comment='Denormalized for fast queries'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspaces_project_id'), 'workspaces', ['project_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('type_config', sa.JSON(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_list', sa.JSON(), nullable=False),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('retry_failed', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('dispositions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_agent_id'), 'campaigns', ['agent_id'], unique=False)
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('manager', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Contact status: new, contacted, qualified, converted, lost'),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contacts_phone_number'), 'contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_index(op.f('ix_contacts_workspace_id'), 'contacts', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('type_data', sa.JSON(), nullable=False, comment='Type-specific interaction data'),
    sa.Column('disposition', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_agent_id'), 'interactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_interactions_contact_id'), 'interactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_interactions_environment_id'), 'interactions', ['environment_id'], unique=False)
    op.create_index(op.f('ix_interactions_interaction_type'), 'interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_interactions_workspace_id'), 'interactions', ['workspace_id'], unique=False)

    # Add all foreign key constraints AFTER tables are created
    op.create_foreign_key('fk_organizations_owner_id', 'organizations', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_users_organization_id', 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_organization_id', 'agents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agents_user_id', 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_audit_logs_organization_id', 'audit_logs', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_audit_logs_user_id', 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_environments_organization_id', 'environments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_privacy_settings_user_id', 'privacy_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_units_organization_id', 'units', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_integrations_organization_id', 'user_integrations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_integrations_user_id', 'user_integrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_profiles_user_id', 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_quotas_user_id', 'user_quotas', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_settings_user_id', 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_deployments_agent_id', 'agent_deployments', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_deployments_environment_id', 'agent_deployments', 'environments', ['environment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_quotas_agent_id', 'agent_quotas', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_versions_agent_id', 'agent_versions', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_versions_created_by', 'agent_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_departments_organization_id', 'departments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_departments_unit_id', 'departments', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_documents_agent_id', 'documents', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_documents_user_id', 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_document_chunks_document_id', 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_projects_department_id', 'projects', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_projects_organization_id', 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_hierarchy_memberships_department_id', 'hierarchy_memberships', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_hierarchy_memberships_organization_id', 'hierarchy_memberships', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_hierarchy_memberships_project_id', 'hierarchy_memberships', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_hierarchy_memberships_unit_id', 'hierarchy_memberships', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_hierarchy_memberships_user_id', 'hierarchy_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_workspaces_organization_id', 'workspaces', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_workspaces_project_id', 'workspaces', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_campaigns_agent_id', 'campaigns', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_campaigns_user_id', 'campaigns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_campaigns_workspace_id', 'campaigns', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_contacts_organization_id', 'contacts', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_contacts_user_id', 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_contacts_workspace_id', 'contacts', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_workspace_members_user_id', 'workspace_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_workspace_members_workspace_id', 'workspace_members', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_interactions_agent_id', 'interactions', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_interactions_contact_id', 'interactions', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_interactions_environment_id', 'interactions', 'environments', ['environment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_interactions_user_id', 'interactions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_interactions_workspace_id', 'interactions', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_workspace_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_interaction_type'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_environment_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_contact_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_agent_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_contacts_workspace_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_phone_number'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_agent_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_workspaces_project_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_hierarchy_memberships_user_id'), table_name='hierarchy_memberships')
    op.drop_index(op.f('ix_hierarchy_memberships_unit_id'), table_name='hierarchy_memberships')
    op.drop_index(op.f('ix_hierarchy_memberships_project_id'), table_name='hierarchy_memberships')
    op.drop_index(op.f('ix_hierarchy_memberships_organization_id'), table_name='hierarchy_memberships')
    op.drop_index(op.f('ix_hierarchy_memberships_department_id'), table_name='hierarchy_memberships')
    op.drop_table('hierarchy_memberships')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_department_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_agent_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_departments_unit_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_slug'), table_name='departments')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_agent_quotas_agent_id'), table_name='agent_quotas')
    op.drop_table('agent_quotas')
    op.drop_index(op.f('ix_agent_deployments_environment_id'), table_name='agent_deployments')
    op.drop_index(op.f('ix_agent_deployments_agent_id'), table_name='agent_deployments')
    op.drop_table('agent_deployments')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_quotas_user_id'), table_name='user_quotas')
    op.drop_table('user_quotas')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_index(op.f('ix_user_integrations_organization_id'), table_name='user_integrations')
    op.drop_index(op.f('ix_user_integrations_integration_type'), table_name='user_integrations')
    op.drop_table('user_integrations')
    op.drop_index(op.f('ix_units_slug'), table_name='units')
    op.drop_index(op.f('ix_units_organization_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_privacy_settings_user_id'), table_name='privacy_settings')
    op.drop_table('privacy_settings')
    op.drop_index(op.f('ix_environments_slug'), table_name='environments')
    op.drop_index(op.f('ix_environments_organization_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_public_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_type'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_sso_subject_id'), table_name='users')
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
